---
inherit_from: https://raw.githubusercontent.com/remove-bg/code-style/main/ruby/.rubocop.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - gemfiles/**/*
    - vendor/bundle/**/*

Layout/LineLength:
  Max: 180

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - spec/integration/*

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 10
