---
inherit_from: https://raw.githubusercontent.com/remove-bg/code-style/main/ruby/.rubocop.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "gemfiles/**/*"

Layout/LineLength:
  Max: 180

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true
